// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"url:jimu/dijit/_filter/EditTable.html":'\x3cdiv\x3e\r\n    \x3cdiv class\x3d"jimu-multiple-set-container"\x3e\r\n      \x3cdiv data-dojo-attach-point\x3d"" class\x3d"items-list-content items-list-header"  \x3e\r\n        \x3cdiv class\x3d"item"\x3e\r\n          \x3cdiv class\x3d"label jimu-ellipsis"\x3e${Nls.value}\x3c/div\x3e\r\n          \x3cdiv class\x3d"label jimu-ellipsis"\x3e${CommonNls.label}\x3c/div\x3e\r\n          \x3cdiv class\x3d"label checkboxHeader jimu-ellipsis"\x3e${CommonNls.defaults}\x3c/div\x3e\r\n          \x3cdiv class\x3d"label lableR jimu-ellipsis"\x3e${CommonNls.actions}\x3c/div\x3e\r\n        \x3c/div\x3e\r\n      \x3c/div\x3e\r\n      \x3cdiv data-dojo-attach-point\x3d"listContent" class\x3d"items-list-content" data-dojo-attach-event\x3d"click:_onListContentClicked, dblclick:_onListContentDblClicked"\x3e\r\n      \x3c/div\x3e\r\n    \x3c/div\x3e\r\n  \x3c/div\x3e'}});
define("dojo/_base/lang dojo/_base/html dojo/Evented dojo/on dojo/dom-attr dojo/_base/declare dijit/_WidgetBase dojo/query dijit/form/ValidationTextBox dijit/form/NumberTextBox dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dojo/text!./EditTable.html jimu/utils".split(" "),function(g,c,m,l,h,n,p,f,q,r,t,u,v,k){return n([p,t,u,m],{templateString:v,currentItem:null,dataList:[],codedValues:null,isNumberField:!0,tableType:"unique",postMixInProperties:function(){this.inherited(arguments);this.CommonNls=
window.jimuNls.common;this.Nls=window.jimuNls.filterBuilder},postCreate:function(){this.inherited(arguments);c.addClass(this.domNode,"jimu-filter-mutcheck-list-value-provider");this.inputType="unique"===this.tableType?"radio":"checkbox"},_onListContentDblClicked:function(a){this.isSearch=!1;a=a.target||a.srcElement;var b=k.getAncestorDom(a,function(a){return c.hasClass(a,"item")},3);if(b&&(c.hasClass(a,"name")||c.hasClass(a,"alias"))){this._dijit?(this.editState="active",this.updateInputDivPre=this.updateInputDiv,
this._dijitPre=this._dijit):this.editState="negative";b=c.hasClass(b,"custom");this.placeHolder=a.innerText;b?c.hasClass(a,"alias")&&this.placeHolder!==this.customLabel?this.currentLabel=a.innerText:this.currentLabel=NaN:this.currentLabel=a.innerText;h.set(a,"innerHTML","");b="";c.hasClass(a,"name")&&(b='\x3cdiv class\x3d"searchBtn"\x3e\x3cdiv class\x3d"jimu-icon jimu-icon-down-arrow-8"\x3e\x3c/div\x3e\x3c/div\x3e');this.updateInputDiv=c.create("div",{"class":"updateInputDiv",innerHTML:'\x3cdiv class\x3d"inputDiv"\x3e\x3c/div\x3e'+
b},a);b=f(".inputDiv",this.updateInputDiv)[0];this.searchBtn=f(".searchBtn",this.updateInputDiv)[0];this.own(l(this.updateInputDiv,"dblclick",g.hitch(this,function(a){a.stopPropagation();a.preventDefault()})));var d={required:!1,intermediateChanges:!1,value:this.currentLabel};this.codedValues&&c.hasClass(a,"name")&&(d.disabled=!0);this.isNumberField&&c.hasClass(a,"name")?(d.constraints={pattern:"#####0.##########"},this._dijit=new r(d)):(d.trim=!0,this._dijit=new q(d));this._dijit.startup();this._dijit.on("keydown",
function(a){13===(a.keyCode||a.which)&&this._dijit.emit("blur")}.bind(this));this._dijit.on("blur",g.hitch(this,function(){var a="Error"!==this._dijit.state?this._dijit.displayedValue:this.currentLabel,b=this._dijit.get("value");""!==b&&b?this.placeHolder===this.customValue&&(b=k.getAncestorDom(this._dijit.domNode,function(a){return c.hasClass(a,"item")},4),c.removeClass(b,"custom"),this.emit("editTable_itemChanged")):a=this.placeHolder;this.newLabel=a;setTimeout(g.hitch(this,function(){this.isSearch||
"active"===this.editState?"active"===this.editState&&(c.hasClass(this.updateInputDiv.parentNode,"name")&&(this.updateInputDivPre.parentNode.nextSibling.innerText=this.newLabel),this.updateInputDivPre.parentNode.innerHTML=this.newLabel,this._dijitPre=this.updateInputDivPre=null,this.editState="negative"):(c.hasClass(this.updateInputDiv.parentNode,"name")&&(this.updateInputDiv.parentNode.nextSibling.innerText=this.newLabel),this.updateInputDiv.parentNode.innerHTML=this.newLabel,this._dijit=null,this.isSearch=
!1)}),300);this.placeHolder=""}));c.setStyle(this._dijit.domNode,"width","100%");this._dijit.placeAt(b);a=f("input",this._dijit.domNode)[1];""===this._dijit.get("value")&&h.set(a,"placeholder",this.placeHolder);a.focus();this.searchBtn&&(this.own(l(this.searchBtn,"click",g.hitch(this,function(a){this.isSearch||(this.isSearch=!0,this.searchTarget=a.target||a.srcElement,this.emit("editTable_openListSelectByName",this.newLabel),a.stopPropagation(),a.preventDefault())}))),this.codedValues&&this.searchBtn.click())}},
_setNewLabel:function(a){a=a?a:this.newLabel;if(this.updateInputDiv&&this.updateInputDiv.parentNode){var b=this.updateInputDiv.parentNode;if(void 0===a)a=this._dijit.get("value");else{b.nextSibling.innerHTML=a;c.setAttr(b,"title",a);if(this.codedValues){var d=this._getCodeFromCodevalueLabel(a);c.setAttr(b,"data",d)}d=b.parentNode;a!==this.customValue&&c.removeClass(d,"custom")}b.innerHTML=a}this._dijit=this.updateInputDiv=null},_onListContentClicked:function(a){a=a.target||a.srcElement;var b=k.getAncestorDom(a,
function(a){return c.hasClass(a,"item")},3);b&&(c.hasClass(a,this.inputType)?("radio"===this.inputType&&!0===this.currentItem&&(this.currentItem=this.getCurrentItem()),c.hasClass(a,"checked")?"radio"!==this.inputType?c.removeClass(a,"checked"):c.hasClass(this.currentItem,"checked")||c.removeClass(a,"checked"):("radio"===this.inputType&&this.currentItem&&c.removeClass(this.currentItem,"checked"),c.addClass(a,"checked"),this.currentItem=a)):c.hasClass(a,"action")&&(c.hasClass(a,"up")?b.previousElementSibling&&
c.place(b,b.previousElementSibling,"before"):c.hasClass(a,"down")?b.nextElementSibling&&c.place(b,b.nextElementSibling,"after"):c.hasClass(a,"delete")&&(c.destroy(b),this.emit("editTable_itemChanged"))))},_getLabelFromCodevalue:function(a){for(var b=a,c=0;c<this.codedValues.length;c++){var e=this.codedValues[c];if(e.value===a){b=e.label;break}}return b},_getCodeFromCodevalueLabel:function(a){for(var b=a,c=0;c<this.codedValues.length;c++){var e=this.codedValues[c];if(e.label===a){b=e.value;break}}return b},
_createTarget:function(a,b,d,e){var f="item";e&&(a=this.customValue,b=this.customLabel,f="item custom");a=a||"";b=b?b:a;d=d?d:"";e=a;var g="";this.codedValues&&a!==this.Nls.addValuePlaceHolder&&(e=this._getLabelFromCodevalue(a),g=this.isNumberField?"data\x3d"+a:"data\x3d'"+a+"'");return c.create("div",{"class":f,innerHTML:'\x3cdiv class\x3d"label name jimu-ellipsis" title\x3d"'+a+'" '+g+"\x3e"+e+'\x3c/div\x3e\x3cdiv class\x3d"label alias jimu-ellipsis" title\x3d"'+b+'"\x3e'+b+'\x3c/div\x3e\x3cdiv class\x3d"label '+
this.inputType+d+' jimu-ellipsis"\x3e\x3c/div\x3e\x3cdiv class\x3d"actions jimu-float-trailing"\x3e\x3cdiv class\x3d"delete action jimu-float-trailing"\x3e\x3c/div\x3e\x3cdiv class\x3d"down action jimu-float-trailing"\x3e\x3c/div\x3e\x3cdiv class\x3d"up action jimu-float-trailing"\x3e\x3c/div\x3e\x3c/div\x3e'},this.listContent)},_destroyTarget:function(a){for(var b=f(".item .name",this.listContent),d=0;d<b.length;d++){var e=b[d];if(h.get(this._dijit.domNode.parentNode,"innerHTML")===a){c.destroy(e.parentNode);
break}}},getCurrentItem:function(){for(var a=f(".item .radio",this.listContent),b=0;b<a.length;b++){var d=a[b];if(c.hasClass(d,"checked"))return d}return null},getListValues:function(){this.listItemsArray=[];this.listValuesArray=[];for(var a=f(".item .name",this.listContent),b=0;b<a.length;b++){var d=a[b],e=k.getAncestorDom(d,function(a){return c.hasClass(a,"item")},3);c.hasClass(e,"custom")||(e=d.innerText,this.codedValues&&(e=c.getAttr(d,"data")),e=this.isNumberField?parseFloat(e):e,e={value:e,
alias:d.nextSibling.innerText,isChecked:!1},this.listItemsArray.push(e),this.listValuesArray.push(d.innerText),c.hasClass(d.nextSibling.nextSibling,"checked")&&(e.isChecked=!0))}return{list:this.listItemsArray,valueList:this.listValuesArray}},setListValues:function(a){h.set(this.listContent,"innerHTML","");for(var b=0;b<a.length;b++){var c=a[b],e="";c.isChecked&&(e=" checked",this.currentItem=!0);this._createTarget(c.value,c.alias,e)}},_initTable:function(){},getDijits:function(){return[this.mutiValuesSelect]},
destroy:function(){this.inherited(arguments)}})});