// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"url:jimu/dijit/_filter/ListMultipleSelectProvider.html":'\x3cdiv\x3e\r\n   \x3cdiv class\x3d"checkBtn" data-dojo-attach-point\x3d"checkedBtn" style\x3d"display:none;"data-dojo-attach-event\x3d"click:_checkedBtnEvent"\x3e\r\n       \x3cdiv data-dojo-attach-point\x3d"checkedNumDiv" class\x3d"checkedNumDiv"\x3e\x3cspan class\x3d"checkedNum" data-dojo-attach-point\x3d"checkedNum"\x3e\x3c/span\x3e${CommonNls.selected}\x3c/div\x3e\r\n       \x3cdiv data-dojo-attach-point\x3d"checkedNameDiv" class\x3d"checkedNum checkedNameDiv jimu-ellipsis"\x3e\x3c/div\x3e\r\n       \x3cdiv class\x3d"jimu-icon jimu-icon-down-arrow-8 checkBtnDownIcon"\x3e\x3c/div\x3e\r\n   \x3c/div\x3e\r\n   \x3cdiv data-dojo-attach-point\x3d"listContent"\x3e\x3c/div\x3e\r\n   \x3cdiv class\x3d"value-multiple-popup" data-dojo-attach-point\x3d"listContentPopup"\x3e\r\n        \x3cdiv data-dojo-attach-point\x3d"listContent"\x3e\x3c/div\x3e\r\n   \x3c/div\x3e\r\n\x3c/div\x3e'}});
define("dojo/Deferred dojo/_base/lang dojo/Evented dojo/_base/html dojo/_base/array dojo/_base/declare dojo/query ./ValueProvider ./ListMultipleSelect dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dojo/text!./ListMultipleSelectProvider.html jimu/utils jimu/dijit/pageControlForQuery jimu/dijit/Popup".split(" "),function(m,e,n,c,g,p,h,q,r,t,u,v,k,w,x){return p([q,t,u,n],{templateString:v,codedValues:null,staticValues:null,showNullValues:!1,cbxPopup:null,pageSize:1E3,pageIndex:1,emptyStr:"",postMixInProperties:function(){this.inherited(arguments);
this.CommonNls=window.jimuNls.common;this.emptyStr=window.apiNls.widgets.FeatureTable.empty},postCreate:function(){this.inherited(arguments);this.noDataTips='\x3cdiv class\x3d"error-tip-section" style\x3d"display: block;"\x3e\x3cspan class\x3d"jimu-icon jimu-icon-error"\x3e\x3c/span\x3e\x3cspan class\x3d"jimu-state-error-text"\x3e'+this.nls.noFilterValueTip+"\x3c/span\x3e\x3c/div\x3e";c.addClass(this.domNode,"jimu-filter-mutcheck-list-value-provider");"ListMultiple_VALUE_PROVIDER"===this.providerType?
(this.controlType="multipleDynamic",this.checkedNumDiv.style.display="block"):"LIST_VALUE_PROVIDER"===this.providerType?(this.controlType="uniqueDynamic",this.checkedNameDiv.style.display="block"):(this.runtime&&"dropdown"===this.selectUI&&("UNIQUE_PREDEFINED_VALUE_PROVIDER"===this.providerType?this.checkedNameDiv.style.display="block":this.checkedNumDiv.style.display="block"),this.controlType="MULTIPLE_PREDEFINED_VALUE_PROVIDER"===this.providerType?"multiplePredefined":"uniquePredefined");this.selectType=
"MULTIPLE_PREDEFINED_VALUE_PROVIDER"===this.providerType?"multiple":"UNIQUE_PREDEFINED_VALUE_PROVIDER"===this.providerType?"unique":"LIST_VALUE_PROVIDER"===this.providerType?"unique":"multiple";this.disPlayLabel="value";!this.runtime||"multiplePredefined"!==this.controlType&&"uniquePredefined"!==this.controlType||(this.disPlayLabel="alias");!this.runtime||"multipleDynamic"!==this.controlType&&"uniqueDynamic"!==this.controlType||(this.isLoadDataAdvanced=!0);this.isNumberField=k.isNumberField(this.fieldInfo.type);
this.pageControlForQuery||(this.pageControlForQuery=new w({pageSize:this.pageSize,pageIndex:1,layerUrl:this.url,fieldInfo:this.fieldInfo,queryWhere:"1\x3d1",layerDefinition:this.layerDefinition,isNumberField:this.isNumberField}),this.pageControlForQuery.on("query_getNewExpr",e.hitch(this,this._resetPageControlNewExpr)));if(!this.listSelect&&(this.listSelectDataList=this.partObj&&this.partObj.valueObj&&this.partObj.valueObj.value?this.partObj.valueObj.value:[],this.listSelect=new r({emptyStr:this.emptyStr,
runtime:this.runtime,pageSize:this.pageSize,selectUI:this.selectUI,controlType:this.controlType,selectType:this.selectType,dataList:this.listSelectDataList,selectedDataList:[],isNumberField:this.isNumberField}),e.isArray(this.listSelectDataList)?this.getCheckedList(this.listSelectDataList):this.listSelect.checkedList=[this.listSelectDataList],this.listSelect.on("listMultipleSelect_itemChecked",e.hitch(this,this._createTarget)),this.listSelect.on("listMultipleSelect_itemUnChecked",e.hitch(this,this._destoryTarget)),
this.listSelect.on("listMultipleSelect_addNextPage",e.hitch(this,this._addNextPage)),this.listSelect.on("listMultipleSelect_searchKey",e.hitch(this,this._searchKey)),this.listSelect.on("listMultipleSelect_searchKeyLocal",e.hitch(this,this._searchKeyLocal)),!this.staticValues&&"function"===typeof this._checkedBtnEvent&&(!this.codedValues||this.codedValues&&this.filterCodedValue)&&this.layerInfo))this.layerInfo.layerObject.on("edits-complete",e.hitch(this,function(){this.layerDataChanged=!0}));"dropdown"===
this.selectUI?(c.setStyle(this.checkedBtn,"display","block"),this._multipleSelectProviderEventHandler=e.hitch(this,this._multipleSelectProviderEvent),document.addEventListener("click",this._multipleSelectProviderEventHandler,{capture:!0})):this.listSelect.placeAt(this.listContent)},filterExpr:null,_resetPageControlNewExpr:function(){var a=this.getDropdownFilterExpr();return this.filterExpr!==a?(this.pageControlForQuery.reset(),this.filterExpr=this.pageControlForQuery.cascadeFilterExprs=a,!0):!1},
_multipleSelectProviderEvent:function(a){a=a.target||a.srcElement;if(this.cbxPopup&&this.cbxPopup.domNode){if(c.isDescendant(a,this.cbxPopup.domNode)||c.isDescendant(a,this.checkedBtn))return;"block"===c.getStyle(this.cbxPopup.domNode,"display")&&(this._resetListSelectState(this),this.cbxPopup.hide())}this.msgDiv&&c.setStyle(this.msgDiv,"display","none")},_checkedBtnEvent:function(a){this._showPopup(a)},_onBeforeDropDownMouseDown:function(){this._tryUpdatingUniqueValues(void 0,!0);return arguments},
_isRestSelectList:!1,_resetListSelectState:function(a){if("block"===c.getStyle(a.listSelect.searchKeyInput,"display")){if("multipleDynamic"===this.controlType){var d=this.listSelect.selectedToggle;c.hasClass(d,"applied")&&(d.toggleButton.uncheck(),c.removeClass(d,"applied"),c.setStyle(this.listSelect.selectedContainer,"display","none"))}a.listSelect.listContainer.scrollTop=0;a.listSelect.queryState=!0;a.listSelect.valueInput.set("value","");this._isRestSelectList=!0}},_createTarget:function(a){this._checkedChanged(1,
a);this.cbxPopup&&("uniqueDynamic"===this.controlType||"uniquePredefined"===this.controlType)&&this.cbxPopup.domNode&&(this._resetListSelectState(this),this.cbxPopup.close())},_destoryTarget:function(a){this._checkedChanged(-1,a)},_checkedChanged:function(a,d){if("multipleDynamic"===this.controlType||"multiplePredefined"===this.controlType&&this.runtime&&"dropdown"===this.selectUI)d&&(a=parseInt(this.checkedNum.innerText,10)+a,this.checkedNum.innerText=a);else if("uniqueDynamic"===this.controlType||
"uniquePredefined"===this.controlType&&this.runtime&&"dropdown"===this.selectUI)"uniqueDynamic"===this.controlType&&(d===this.emptyStr?c.addClass(this.checkedNameDiv,"checkedEmptyNameDiv"):c.removeClass(this.checkedNameDiv,"checkedEmptyNameDiv")),this.checkedNameDiv.innerText=d?d:this.checkedNameDiv.innerText;this.listSelect.set("displayedValue","12345678");this.emit("change")},_clearCheckedTxt:function(){if(this.runtime&&"dropdown"===this.selectUI){if("multipleDynamic"===this.controlType||"multiplePredefined"===
this.controlType)this.checkedNum.innerText=0;else if("uniqueDynamic"===this.controlType||"uniquePredefined"===this.controlType)this.checkedNameDiv.innerText="";this.listSelect.checkedList=[];this.listSelect.valueInput.set("value","");if("multipleDynamic"===this.controlType){var a=this.listSelect.selectedToggle;c.hasClass(a,"applied")&&(a.toggleButton.uncheck(),c.setStyle(this.listSelect.selectedContainer,"display","none"))}}this.listSelect.set("displayedValue","12345678");this.emit("change")},_layerDataChangedCallback:function(){this.layerDataChanged&&
(this.pageControlForQuery.reset(),this.listSelect.ifFristPage=!0,this.layerDataChanged=!1)},_addNextPage:function(){this.listSelect&&(this._showLoadingIcon(),this._layerDataChangedCallback(),this.pageControlForQuery.getPageValueDef(this.listSelect.ifFristPage).then(e.hitch(this,function(a){this.listSelect.isCacheFinish=this.pageControlForQuery._isUniqueValueCacheFinish;this.listSelect.ifFristPage&&this._checkIfNoData(a)||(this.listSelect.setCBXData(a,!0,this.listSelect.ifFristPage),this._hideLoadingIcon())}),
e.hitch(this,function(a){console.log(a);this.listSelect.queryState=!1;this._hideLoadingIcon()})))},_searchKey:function(a){this.listSelect&&(this._showLoadingIcon(),this._layerDataChangedCallback(),this.pageControlForQuery._searchKey(a).then(e.hitch(this,function(a){this.listSelect.setCBXContentBySearch(a);this._resetPopupStyles(!a.length);this._hideLoadingIcon()}),e.hitch(this,function(a){console.log(a);this._hideLoadingIcon()})))},_searchKeyLocal:function(a,d){if(this.listSelect){"uniqueDynamic"===
this.controlType&&this._isRestSelectList&&(this.listSelect.keyQueryMode=!1,this._isRestSelectList=this.listSelect.cacheQueryMode=!1);this._showLoadingIcon();var b=this.pageControlForQuery._searchKeyLocal(a);""===a&&0===b.length?(this.layerDataChanged=!0,this._layerDataChangedCallback(),this._addNextPage()):this.listSelect.setCBXContentBySearch(b,d);this._resetPopupStyles(!0);this._hideLoadingIcon()}},queryByPage:function(){var a=this.pageControlForQuery.queryByPage(this.listSelect.ifFristPage);a.then(e.hitch(this,
function(d){a.resolve(d)}),e.hitch(this,function(d){console.log(d);a.reject(d)}))},getCheckedList:function(a){this.listSelect.checkedList=[];g.forEach(a,e.hitch(this,function(a){var b;e.isObject(a)?a.isChecked&&(b=a.value):b=a;if(b||0===b)b=this.isNumberField?parseFloat(b):b,this.listSelect.checkedList.push(b)}))},getCheckedStrsList:function(a){var d=[];g.forEach(a,e.hitch(this,function(a){var b;e.isObject(a)?a.isChecked&&(b=a[this.disPlayLabel]):b=a;(b||0===b)&&d.push(b)}));return d},showContent:function(a){var d=
new m;this.getCheckedList(this.valueList);this.listSelect.codedValues=!1;this.listSelect.disPlayLabel="value";var b;if("multiplePredefined"===this.controlType||"uniquePredefined"===this.controlType)return this.runtime&&(this.listSelect.disPlayLabel="alias"),(b=this._checkIfNoData(this.valueList))||this.listSelect.setCBXData(this.valueList,!0,a),this._hideLoadingIcon(),d.resolve(b),d;if(this.staticValues)return b=this._setValueForStaticValues(this.staticValues),d.resolve(b),d;if(this.codedValues)if(this.filterCodedValue)this.listSelect.codedValues=
!0;else return b=this._setValueForStaticValues(this.codedValues),d.resolve(b),d;this._showLoadingIcon();if("multipleDynamic"===this.controlType||"uniqueDynamic"===this.controlType)this._layerDataChangedCallback(),this.pageControlForQuery.getPageValueDef(a).then(e.hitch(this,function(c){this.listSelect.isCacheFinish=this.pageControlForQuery._isUniqueValueCacheFinish;c=this._handleCodedValue(c);(b=this._checkIfNoData(c))||this.listSelect.setCBXData(c,!0,a);this._hideLoadingIcon();d.resolve(b)}),e.hitch(this,
function(a){console.log(a);this._hideLoadingIcon();d.reject(a)}));return d},_handleCodedValue:function(a){if(!this.codedValues)return a;this.listSelect.disPlayLabel="label";a=g.map(a,function(a){return a.value});a=k._getValues(this.layerDefinition,this.fieldPopupInfo,this.fieldName,a);this.pageControlForQuery._codedvalueCache=a;"uniqueDynamic"===this.controlType&&this._setCheckedName(this.listSelect.checkedList?this.listSelect.checkedList[0]:"",a);this.listSelect._updateCheckedLabelList(this.codedValues);
return a},_showDropdown:function(a){var d=c.position(a.target),b;b=this.isInFilterSet?this.domNode.parentNode.parentNode.parentNode:this.domNode.parentNode;var e=c.position(b);if("none"!==c.getStyle(this.listContentPopup,"display"))c.setStyle(this.listContentPopup,"display","none");else{g.forEach(h(".value-type-popup",b),function(a){c.setStyle(a,"display","none")},this);c.place(this.listContentPopup,b);var f;f=c.hasClass(h(".desktop-add-section",b.parentNode)[0],"hidden")?-5:30;f=d.y-e.y-b.parentNode.scrollTop+
f;f+170>b.parentNode.scrollHeight&&(f=b.parentNode.scrollHeight-170-40);window.isRTL?d=d.x-e.x+20:(d=d.x-e.x-100-90,d+150>b.clientWidth&&(d=b.clientWidth-150));c.setStyle(this.listContentPopup,{display:"block",left:d+"px",top:f+"px"});a.stopPropagation()}},_calculatePopup:function(){var a=c.position(this.domNode.parentNode),d=c.position(document.body).h,b=a.y+30;d-b<this._cbxHeight&&(b=a.y-this._cbxHeight);return{left:a.x,top:b}},_cbxWidth:210,_cbxHeight:362,popupIsNoData:!1,isPopupLoading:!1,isLoadDataAdvanced:!1,
_showPopup:function(a){if(!this.isPopupLoading)if(this.cbxPopup&&this.cbxPopup.domNode&&"block"===c.getStyle(this.cbxPopup.domNode,"display"))this._resetListSelectState(this),this.cbxPopup.hide();else{var d=this._resetPageControlNewExpr();d&&this.cbxPopup&&(this.cbxPopup.close(),this._clearCheckedTxt());var b=this._calculatePopup();this._cbxWidth=c.getStyle(this.checkedBtn,"width");if(!d&&this.cbxPopup&&this.cbxPopup.domNode&&!this.layerDataChanged)this.popupIsNoData?this._checkIfNoData([]):(this._resetItemWidth(),
c.setStyle(this.cbxPopup.domNode,{display:"block",left:b.left+"px",top:b.top+"px",width:this._cbxWidth+"px"}),this.cbxPopup.show(),this.listSelect.valueInput&&this.listSelect.valueInput.focus(),this.listSelect.queryState=!1,c.setStyle(this.cbxPopup.overlayNode,"display","none"));else{this.isPopupLoading=!0;this._showDataQueryingIcon();var l=this.showContent(!0);l.then(e.hitch(this,function(a){this.isPopupLoading=!1;this._hideDataQueryingIcon();this.popupIsNoData=a;a?this.isLoadDataAdvanced&&(this.isLoadDataAdvanced=
!1):(this.cbxPopup=new x({width:this._cbxWidth,height:this._cbxHeight,content:this.listSelect.domNode,titleLabel:this.layerDefinition.name+"("+this.fieldName+")",isResize:!1,onClose:e.hitch(this,function(){this.cbxPopup.hide();return!1}),buttons:[]}),c.setStyle(this.cbxPopup.contentContainerNode,{top:"0px",bottom:"3px",left:"0px",right:"0px"}),c.destroy(this.cbxPopup.titleNode),c.setStyle(this.cbxPopup.domNode,{display:"block",left:b.left+"px",top:b.top+"px",border:"1px solid #999"}),c.setStyle(this.cbxPopup.overlayNode,
"display","none"),setTimeout(e.hitch(this,function(){this._resetPopupStyles(!1,!0);this.isLoadDataAdvanced?(this.isLoadDataAdvanced=!1,c.setStyle(this.cbxPopup.domNode,"display","none")):this.listSelect.valueInput&&this.listSelect.valueInput.focus()},80)))}),e.hitch(this,function(a){this.isPopupLoading=!1;console.log(a);l.reject(a)}))}a&&a.stopPropagation()}},_itemContainerH:300,_resetPopupStyles:function(a,d){var b=this._itemContainerH,e=c.getStyle(this.listSelect.listContent,"height");0===e&&this.cbxPopup&&
this.cbxPopup.domNode&&"none"===c.getStyle(this.cbxPopup.domNode,"display")&&(e=this.popupInitHeight);d&&(this.popupInitHeight=e);!a||this.listSelect.codedValues||this.pageControlForQuery._isUniqueValueCacheFinish||(e+=25);this.pageControlForQuery._isUniqueValueCacheFinish&&"block"===c.getStyle(this.listSelect.noDataTips,"display")&&(e+=30);b=e<b?e:b;c.setStyle(this.listSelect.listContainer,"height",b+"px");c.setStyle(this.listSelect.selectedContainer,"height",b+30+"px");"multipleDynamic"===this.controlType?
b=b+30+30:"uniqueDynamic"===this.controlType&&(b+=30);this._cbxHeight=b+10;a=this._calculatePopup();this._cbxWidth=c.getStyle(this.checkedBtn,"width");c.setStyle(this.cbxPopup.domNode,{width:this._cbxWidth+"px",left:a.left+"px",top:a.top+"px",height:this._cbxHeight+"px"});this._resetItemWidth()},_resetItemWidth:function(){var a=this._cbxWidth-20;"uniqueDynamic"===this.controlType||this.runtime&&"uniquePredefined"===this.controlType&&"dropdown"===this.selectUI||!this.runtime&&("multiplePredefined"===
this.controlType||"uniquePredefined"===this.controlType)||(a=!this.runtime||"dropdown"===this.selectUI||"uniquePredefined"!==this.controlType&&"multiplePredefined"!==this.controlType?a-30:a-15);window.isRTL&&(a-=3);this.listSelect._itemLabelW=a;h(".item .label",this.listSelect.listContent).style({"max-width":a+"px"})},_setValueForStaticValues:function(a){this.listSelect.codedValues=!0;if(a){this.pageControlForQuery._codedvalueCache=a;var c=this._checkIfNoData(a);c||(this.listSelect.disPlayLabel="label",
this.listSelect.setCBXData(a,!0,!0));return c}return!1},_checkIfNoData:function(a){if(this.runtime&&"dropdown"===this.selectUI){if(a&&0<a.length)return!1;this.msgDiv?c.setStyle(this.msgDiv,"display","block"):(this.msgDiv=document.createElement("div"),c.addClass(this.msgDiv,"jimu-filter-list-value-provider-tip-container"),this.msgDiv.innerHTML=this.noDataTips,this.checkedBtn.parentNode.appendChild(this.msgDiv));return!0}return!1},getDijits:function(){return[this.listSelect]},_setCheckedName:function(a,
d){var b=a;if(d=d?d:this.codedValues){for(var e=!1,f=0;f<d.length;f++){var g=d[f];if(g.value===a){b=g.label;e=!0;break}}e||(b=this.emptyStr,this.valueList=[],this.listSelect&&(this.listSelect.checkedList=[]))}else void 0===a?(b=this.emptyStr,c.addClass(this.checkedNameDiv,"checkedEmptyNameDiv")):c.removeClass(this.checkedNameDiv,"checkedEmptyNameDiv");this.checkedNameDiv.innerText=b},setValueObject:function(a){a.value=a.value||0===a.value?a.value:[];this.valueList=a.value;"multipleDynamic"===this.controlType?
(this.checkedNum.innerText=this.valueList.length,this.isLoadDataAdvanced&&this._checkedBtnEvent()):"uniqueDynamic"===this.controlType?(a=this.valueList,e.isArray(a)&&0===a.length&&(a=void 0),this._setCheckedName(a),this.valueList=[this.valueList],this.isLoadDataAdvanced&&this._checkedBtnEvent()):(this.runtime&&"dropdown"===this.selectUI&&(a=[],"value"===this.disPlayLabel?(this.getCheckedList(this.valueList),a=this.listSelect.checkedList):a=this.getCheckedStrsList(this.valueList),"UNIQUE_PREDEFINED_VALUE_PROVIDER"===
this.providerType?this.checkedNameDiv.innerText=0<this.listSelect.checkedList.length?a[0]:"":this.checkedNum.innerText=a.length),this.showContent(!0),setTimeout(e.hitch(this,function(){this._cbxWidth=c.getStyle(this.listSelect.listContent,"width");this._resetItemWidth()}),50))},tryGetValueObject:function(){if(this.isValidValue())return this.getValueObject();if(this.isEmptyValue()){var a=null,a="multipleDynamic"===this.controlType||"multiplePredefined"===this.controlType?[]:"string"===this.shortType?
"":null;return{isValid:!0,type:this.partObj.valueObj.type,value:a,checkedValue:"string"===this.shortType?"":null}}return null},getValueObject:function(){if(this.isValidValue()){var a;a="multipleDynamic"===this.controlType||"uniqueDynamic"===this.controlType?this.listSelect.getListCheckedValues():this.listSelect.getListValues();"uniqueDynamic"===this.controlType&&(a=e.isArray(a)?a[0]:a);!this.runtime&&this.cbxPopup&&this.cbxPopup.domNode&&(this.cbxPopup.onClose=e.hitch(this,function(){return!0}),this.cbxPopup.close());
return{isValid:!0,type:this.partObj.valueObj.type,value:a}}return null},setRequired:function(a){this.listSelect.set("required",a)},_showDataQueryingIcon:function(){this._validatingNode||(this._validatingNode=c.create("div",{"class":"jimu-circle-loading"},this.checkedBtn));c.setStyle(this._validatingNode,"display","block")},_hideDataQueryingIcon:function(){c.setStyle(this._validatingNode,"display","none")},_showLoadingIcon:function(){this.listSelect&&this.listSelect.listContainer&&c.addClass(this.listSelect.listContainer,
"jimu-circle-loading")},_hideLoadingIcon:function(){this.listSelect&&this.listSelect.listContainer&&c.removeClass(this.listSelect.listContainer,"jimu-circle-loading")},destroy:function(){this._multipleSelectProviderEventHandler&&document.removeEventListener("click",this._multipleSelectProviderEventHandler,{capture:!0});this.inherited(arguments)},destroyProvider:function(){this.listSelect&&this.listSelect.destroy();this.listSelect=null}})});