# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# # # #  If Site Does Not Load on GH-PAGES:  # # # #
# # # #  CHECK BASEURL SETTING !!!           # # # #

# SITE SETTINGS
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Serge Prokofiev Archive as Data
tag: A Digital Humanities Project
email: ne99@columbia.edu m.saccomano@columbia.edu
description: Visualizations and data files drawn the from Serge Prokofiev Archive finding aid.

# ! ! -- BASEURL SETTINGS -- ! !

# To display website on LOCAL server, set baseurl to ""
# To deplay website on GH-PAGES, set baseurl to "spa-data/"

#baseurl: "/spa-data"
baseurl: ""

url: "" # the base hostname & protocol for your site, e.g. http://example.com



github_username:  spa-data

# BUILD SETTINGS
markdown: kramdown
theme: minima

plugins:
  - jekyll-feed

collections:
    verovio:
      output: true
      permalink: /_verovio/:path/

#Found the issue! If you're specifying output or permalink for a collection, you'll need to specify the collection itself as a hash and not part of an array.

#So in your _config.yml, use this instead:

#collections:
#  projects:
#    output: true
#    permalink: /projects/:path/

#https://github.com/jekyll/jekyll/issues/4097
      # output: true


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
