// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"url:widgets/Swipe/MultSelector/MultSelector.html":'\x3cdiv class\x3d"mult-selector"\x3e\r\n\t\x3cdiv data-dojo-type\x3d"dojox/form/CheckedMultiSelect" multiple\x3d"true" dropDown\x3d"true"\r\n\t\tdata-dojo-attach-point\x3d"selector"\x3e\x3c/div\x3e\r\n\x3c/div\x3e'}});
define("dojo/Evented dojo/_base/declare dojo/_base/lang dijit/_WidgetBase dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dojo/on dojo/query dojo/_base/html dojo/text!./MultSelector.html jimu/dijit/CheckBox dijit/form/Select dojox/form/CheckedMultiSelect dijit/form/ValidationTextBox xstyle/css!dojox/form/resources/CheckedMultiSelect.css".split(" "),function(l,m,h,n,p,q,k,r,b,t){return m([n,p,q,l],{templateString:t,_LAST_VALUEL:"",postCreate:function(){this.inherited(arguments)},startup:function(){this.own(k(this.selector,
"click",h.hitch(this,function(a){"INPUT"===a.target.nodeName&&this.selector.dropDownButton.toggleDropDown()})));this.own(k(this.selector,"change",h.hitch(this,function(a){this._updateMultSelectorLabel(this._getOptionsLabelsByValues(a));this._LAST_VALUEL.toString()!==a.toString()&&(this.selector.dropDownButton.toggleDropDown(),this.selector.dropDownButton.toggleDropDown(),this.emit("change",a),this._LAST_VALUEL=a)})));this.inherited(arguments)},initOptions:function(a,c){this.disable();this._initMultSelectorLabel();
var d=null;c&&(d=this.selector.getOptions());this.selector.removeOption(this.selector.getOptions());for(var e=[],g=0,b=a.length;g<b;g++){var f=a[g];this.selector.addOption(f);this._hasOptionMultSelected(f,c?d:a)&&e.push(f.value)}this.selector.set("value",e);this._updateMultSelectorLabel(this._getOptionsLabelsByValues(e));this.enable()},setOptions:function(a){this.selector.set("options",a)},getOptions:function(){return this.selector.get("options")},reset:function(){this.selector.set("options",[{value:"",
label:""}]);this.selector.reset()},setValue:function(a){this.setConfig(a)},setConfig:function(a){this._setMultSelectorEmpty();this.selector.set("value",a)},getConfig:function(){return this.selector.getValue()},disable:function(){this.selector.set("disabled",!0);this._DISABLED=!0},enable:function(){this.selector.set("disabled",!1);this._DISABLED=!1},_initMultSelectorLabel:function(){this.selector.labelDiv&&(b.empty(this.selector.labelDiv),b.destroy(this.selector.labelDiv),this.selector.labelDiv=null);
var a=r(".dijitButtonText",this.selector.dropDownButton.buttonNode)[0];b.addClass(a,"hide");this.selector.labelDiv=b.create("div",{"class":"dijitReset dijitInline dijitButtonText multselector-label-container"},a,"after");this._updateMultSelectorLabel([this.nls.defaultLayerHolder])},_setMultSelectorEmpty:function(){this.selector.set("value",[]);this._updateMultSelectorLabel([this.nls.defaultLayerHolder])},_updateMultSelectorLabel:function(a){b.empty(this.selector.labelDiv);a&&0!==a.length||this._setMultSelectorEmpty();
for(var c=0,d=a.length;c<d;c++)b.create("div",{"class":"dijitReset dijitButtonText multselector-label",innerHTML:a[c]},this.selector.labelDiv)},_getOptionsLabelsByValues:function(a){for(var c=this.getOptions(),d=[],e=0,b=c.length;e<b;e++)for(var h=c[e],f=0,k=a.length;f<k;f++)h.value===a[f]&&d.push(h.label);return d},_hasOptionMultSelected:function(a,c){for(var d=0,b=c.length;d<b;d++){var g=c[d];if(g.value===a.value&&!0===g.selected)return!0}return!1}})});