// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"url:widgets/DataAggregation/js/UI/templates/FeatureToolbar.html":'\x3cdiv class\x3d"float-right no-select"\x3e\r\n  \x3ctable class\x3d"control-table table-layout" cellpading\x3d"0"\x3e\r\n    \x3ctbody\x3e\r\n      \x3ctr class\x3d"feature-toolbar-row"\x3e\r\n        \x3ctd title\x3d"${nls.featureToolbar.edit}"\x3e\r\n          \x3cdiv class\x3d"float-left bg-ft-img bg-edit feature-toolbar-btn" data-dojo-attach-event\x3d"onclick:_toggleEdit"\x3e\x3c/div\x3e\r\n        \x3c/td\x3e\r\n        \x3ctd title\x3d"${nls.featureToolbar.cancel}"\x3e\r\n          \x3cdiv class\x3d"bg-ft-img bg-cancel feature-toolbar-btn" data-dojo-attach-event\x3d"onclick:_cancel"\x3e\x3c/div\x3e\r\n        \x3c/td\x3e\r\n        \x3ctd title\x3d"${nls.featureToolbar.save}"\x3e\r\n          \x3cdiv class\x3d"float-right bg-ft-img bg-save feature-toolbar-btn" data-dojo-attach-event\x3d"onclick:_save"\x3e\x3c/div\x3e\r\n        \x3c/td\x3e\r\n      \x3c/tr\x3e\r\n    \x3c/tbody\x3e\r\n  \x3c/table\x3e\r\n\x3c/div\x3e'}});
define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/Evented dojo/query dojo/dom-class dojo/dom-construct dojo/Deferred dijit/_WidgetBase dijit/_TemplatedMixin dojo/on dojox/gfx/fx dojo/text!./templates/FeatureToolbar.html esri/toolbars/edit jimu/dijit/Message jimu/dijit/Popup jimu/utils esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleLineSymbol esri/Color esri/graphic esri/geometry/webMercatorUtils".split(" "),function(v,d,l,w,n,q,x,h,y,z,m,A,B,C,p,D,r,t,u,E,F,G){return v([y,z,w],
{templateString:B,baseClass:"cf-feature-toolbar",declaredClass:"FeatureToolbar",label:"FeatureToolbar",parent:null,nls:null,map:null,appConfig:null,config:null,feature:null,layer:null,theme:"",isDarkTheme:"",locators:[],styleColor:"",featureView:null,_editToolbar:null,csvStore:null,_isAddressFeature:!0,_stageLayer:null,constructor:function(a){d.mixin(this,a);this._syncDisabled=this._locateDisabled=this._cancelDisabled=this._saveDisabled=this._editDisabled=!0;this._hasAttributeEdit=!1;this.own(m(this.featureView,
"attribute-change",d.hitch(this,this._attributeChange)));this._hasAddressEdit=!1;this.own(m(this.featureView,"address-change",d.hitch(this,this._addressChange)));this._hasGeometryEdit=!1;this.own(m(this._editToolbar,"graphic-move-stop",d.hitch(this,this._graphicMoveStop)));this.own(m(this.featureView,"address-located",d.hitch(this,this._graphicMoveStop)));this.locator=this._getLocator(0);this._initOriginalValues()},postCreate:function(){this.inherited(arguments);this._darkThemes=["DartTheme","DashboardTheme"];
this.updateImageNodes()},startup:function(){this.inherited(arguments);this._started=!0;this.featureView._toggleEditControls(this._editDisabled)},_getLocator:function(a){for(var b;a<this.csvStore._geocodeSources.length;a++)if(this.locatorSource=this.csvStore._geocodeSources[a],this.locatorSource.locator.locationToAddress){b=this.locatorSource.locator;this._locatorIndex=a;break}b&&(b.outSpatialReference=this.map.spatialReference,b.countryCode=this.locatorSource.countryCode);return b},_initOriginalValues:function(){this._originalValues=
d.clone(this.featureView.feature)},_attributeChange:function(a){this._hasAttributeEdit=a;this.featureView.isDuplicate&&this.featureView._useGeomFromLayer?this._updateSaveAndCancel(!this._hasAttributeEdit):this._updateSaveAndCancel(!(this._hasAttributeEdit||this._hasGeometryEdit));this._updateSync(!this.featureView._validateAddressDifference())},_addressChange:function(a){this._hasAddressEdit=a;this._updateLocate(!a)},_graphicMoveStop:function(a){this.featureView.isShowing&&(this._hasGeometryEdit=
!0,this.featureView.isDuplicate&&this.featureView._useGeomFromLayer?this._updateSaveAndCancel(!this._hasAttributeEdit):this._updateSaveAndCancel(!(this._hasAttributeEdit||this._hasGeometryEdit)),this.map.infoWindow.setFeatures(this.featureView._feature),this.map.infoWindow.select(0),a?this._reverseLocate(a.graphic.geometry).then(d.hitch(this,function(){this._hasAddressEdit=!0;this._updateLocate(!0);this.featureView._validateAddressDifference()&&this._updateSync(!1);this.locator=this._getLocator(0)}),
function(a){this.locator=this._getLocator(0);new p(a)}):this.featureView._validateAddressDifference()&&this._updateSync(!1))},_reverseLocate:function(a){var b=new h;if(this._isAddressFeature)this.locator.locationToAddress(a,100,d.hitch(this,function(a){this.featureView._updateAddressFields(a.address,!1);b.resolve({address:a.address})}),d.hitch(this,function(c){this._getNextLocator()?this._reverseLocate(a).then(function(a){b.resolve(a)}):(this.featureView._updateAddressFields({},!1),b.reject({message:c.message}))}));
else{var c;a.spatialReference.isWebMercator&&a.spatialReference.isWebMercator()&&(c=G.webMercatorToGeographic(a));this.featureView._updateAddressFields(c||a,!1);b.resolve({geometry:a})}return b},_disableEdit:function(){this._editDisabled=!1;this._toggleEdit()},_toggleEdit:function(){this._editDisabled=!this._editDisabled;this._updateEdit(this._editDisabled);this.featureView._toggleEditControls(this._editDisabled);this.map.infoWindow.isShowing&&this.map.infoWindow.hide();this._editDisabled?(this._enableEdit(!1),
this._undoEdits(),this._updateSaveAndCancel(!0),this._updateSync(!0),this.map.infoWindow.clearFeatures()):(this.featureView.isDuplicate?(this._flashFeatures([this.featureView._useGeomFromFile?this.featureView._feature:this.featureView._editFeature]),this.featureView._useGeomFromFile?(this._enableEdit(!0),this._updateSaveAndCancel(!(this._hasAttributeEdit||this._hasGeometryEdit))):this._updateSaveAndCancel(!this._hasAttributeEdit)):(this._enableEdit(!0),this._flashFeatures([this.featureView._feature]),
this._updateSaveAndCancel(!(this._hasAttributeEdit||this._hasGeometryEdit))),this._updateLocate(!this._hasAddressEdit),this._hasGeometryEdit&&this._locateDisabled||this.featureView.isDuplicate&&this.featureView._useValuesFromLayer?this._updateSync(!this.featureView._validateAddressDifference()):this._updateSync(!0))},_enableEdit:function(a){a?this._editToolbar.activate(C.MOVE,this.featureView._feature):(this._editToolbar.refresh(),this._editToolbar.deactivate())},_undoEdits:function(){this._hasAttributeEdit&&
(this.featureView.resetAttributeValues(),this._hasAttributeEdit=!1);this._hasAddressEdit&&(this.featureView.resetAddressValues(this._originalValues),this._hasAddressEdit=!1);this._hasGeometryEdit?(this.featureView.resetGeometry(this._originalValues.geometry),this._hasGeometryEdit=!1):this.featureView.resetFromLayerRows();this._updateSync(!this.featureView._validateAddressDifference());this._updateLocate(!0)},_locate:function(){this._locateDisabled||this._locateFeature().then(d.hitch(this,function(){this._hasAddressEdit=
!1;this._updateLocate(!0)}))},_cancel:function(){if(!this._cancelDisabled)var a=new D({titleLabel:this.nls.featureToolbar.cancelTitle,width:400,autoHeight:!0,content:x.create("div",{innerHTML:this.nls.featureToolbar.cancelMessage,style:"padding-bottom: 10px;"}),buttons:[{label:this.nls.yes,onClick:d.hitch(this,function(){a.close();a=null;this._undoEdits();this._updateSaveAndCancel(!0);this._panToAndSelectFeature(this.featureView.isDuplicate&&this.featureView._useGeomFromLayer?this.featureView._editFeature:
this.featureView._feature)})},{label:this.nls.no,onClick:d.hitch(this,function(){a.close()})}],onClose:d.hitch(this,function(){a=null})})},_save:function(a){var b=this.featureView._feature;if(!this._saveDisabled||!0===a){!0!==a&&(this._setFieldValues(this.featureView),this._setAddressValues(this.featureView),this.featureView.feature.geometry=b.geometry,this._originalValues.geometry=b.geometry,this.featureView.isDuplicate&&(this._originalValues.duplicateGeometry=b.geometry));if(-1===this.featureView.label.indexOf("UnMatched")&&
-1===this.featureView.label.indexOf("DuplicateFeatures"))this._updateLayer(this._stageLayer,null,[b],null,!0,!1).then(d.hitch(this,function(a){a&&"success"===a.status&&this._updateFeatureListLabel(b)}));else if(this.featureView.isDuplicate&&!0!==a)this.featureView._updateDuplicateAttributes(null,!0),this._updateLayer(this.layer,null,[b],null,!0,!1).then(d.hitch(this,function(a){a&&"success"===a.status&&this._updateFeatureListLabel(b)}));else{var c=b.attributes[this.layer.objectIdField];this._updateLayer(this.layer,
null,null,[b],!0,!1).then(d.hitch(this,function(f){f&&"success"===f.status&&this.featureView._parentFeatureList.removeFeature(this.featureView.feature,c).then(d.hitch(this,function(){l.forEach(this.featureView._skipFields,d.hitch(this,function(a){delete b.attributes[a]}));this._updateLayer(this._stageLayer,[b],null,null,!0,!1).then(d.hitch(this,function(c){c&&"success"===c.status&&(c.hasOwnProperty("objectId")&&(this.featureView.feature.fieldInfo.filter(d.hitch(this,function(a){return a.name===this._stageLayer.objectIdField}))[0].value=
c.objectId),this.featureView.feature.label=b.attributes[this.csvStore.labelField],c=this.parent._pageContainer.getViewByTitle("Review"),c.matchedFeatureList.addFeature(this.featureView.feature),c.matchedFeatureList.resetFeatureList(),c._updateReviewRows(!0===a?"duplicate":"unmatched"))}))}))}))}!0!==a&&(this._updateSaveAndCancel(!0),this._toggleEdit())}},_updateFeatureListLabel:function(a){var b=this.csvStore.labelField;a=a.attributes[b];var c=r.stripHTML(a.toString?a.toString():"");c!==this.featureView.featureListLabel.innerHTML&&
("."!==this.csvStore.decimalSeperator&&(a=this.feature.fieldInfo.filter(function(a){return a.name===b&&a.needsFormat&&-1===[null,void 0].indexOf(c)}))&&a.hasOwnProperty("length")&&0<a.length&&(c=r.localizeNumber(c),a[0].formattedValue=c),this.featureView.featureListLabel.innerHTML=c,this.featureView.pageTitleDiv.innerHTML=c)},_updateLayer:function(a,b,c,f,g,e){var k=new h;a.applyEdits(b,c,f).then(d.hitch(this,function(a){var b={status:"success"};this.featureView.isDuplicate&&(this._hasGeometryEdit&&
this.featureView._useGeomFromFile&&(this._fileGeometryModified=!0),this._hasAttributeEdit&&this.featureView._useValuesFromFile&&(this._fileValuesModified=!0));g&&(this._hasAttributeEdit=this._hasGeometryEdit=!1);a&&a.hasOwnProperty("length")&&0<a.length&&a[0].hasOwnProperty("objectId")&&(b.objectId=a[0].objectId);!e&&c&&c.hasOwnProperty("length")&&0<c.length&&(a=this.featureView.parent._pageContainer.getViewByTitle("Review"),a._updateNode(a.submitButton,!0));k.resolve(b)}),d.hitch(this,function(a){new p({message:this.nls.warningsAndErrors.saveError});
k.resolve({status:"error",error:a})}));return k},_setFieldValues:function(a){var b=a._useValuesFromFile,c=b?a._changedFileAttributeRows:a._changedLayerAttributeRows,f=a._feature,d=a.feature;l.forEach(a.featureControlTable.rows,function(a){if(a.isEditRow&&-1<c.indexOf(a.rowIndex)){var e=a.parent.isDuplicate&&!b?a.layerValueTextBox:a.fileValueTextBox;f.attributes[a.fieldName]=e.value;d.fieldInfo.filter(function(b){return b.name===a.fieldName})[0].value=e.value;a.parent.isDuplicate&&!b?a.layerValue=
e.value:a.fileValue=e.value;if(e.textbox)e.textbox.title=e.value;else if(e.domNode){var g=e.attr("displayedValue");e.domNode.title=g?g:e.value}}})},_setAddressValues:function(a){var b=a._getAddress(),c=this.csvStore.matchFieldPrefix;a.isDuplicate&&a._useGeomFromLayer||l.forEach(a.addressFields,function(f){var d=c+f.keyField;a.feature.fieldInfo.filter(function(a){return a.name===d})[0].value=b[d];for(var e,k=0;k<a.locationControlTable.rows.length&&(e=a.locationControlTable.rows[k],!e.isAddressRow||
e.keyField!==f.keyField);k++);e.addressValueTextBox.textbox?e.addressValueTextBox.textbox.title=b[d]:e.addressValueTextBox.domNode&&(f=e.addressValueTextBox.attr("displayedValue"),e.addressValueTextBox.domNode.title=f?f:e.addressValueTextBox.value);e.addressValue=b[d]})},_updateFeature:function(a,b,c){var f=this.featureView;f.feature.geometry=a;f._feature.geometry=a;a=[f._feature];f.isDuplicate&&(this._hasGeometryEdit=f._editFeature.geometry.x!==f._feature.geometry.x||f._editFeature.geometry.y!==
f._feature.geometry.y);b||this._updateLayer(f.layer,null,a,null,!1,c).then(d.hitch(this,function(a){a&&"success"===a.status&&(this._panToAndSelectFeature(f._feature),f.emit("address-located"))}))},_locateFeature:function(a){var b=new h,c=this.featureView._getAddressFieldsValues();this._isAddressFeature?this._addressToLocation({address:c,countryCode:this.locatorSource.countryCode,outFields:["ResultID","Score"]}).then(d.hitch(this,function(c){this.locator=this._getLocator(0);this._updateFeature(c.location,
a,!0);b.resolve({feature:this.featureView.feature,address:c.address})}),function(a){new p({message:a.message})}):(c=this.csvStore._getGeometry(c[this.xField],c[this.yField]),this._updateFeature(c,a,!0),b.resolve({feature:this.featureView.feature,geometry:c}));return b},_addressToLocation:function(a){var b=new h;a.maxLocations=1;this.locator.addressToLocations(a,d.hitch(this,function(c){var f=this.csvStore.minScore,d;c&&0<c.length?(l.forEach(c,function(a){"undefined"===typeof d&&a.score>=f&&(d=a);
d&&a.score>d.score&&(d=a)}),d?b.resolve(d):this._getNextLocator()?this._addressToLocation(a).then(function(a){b.resolve(a)}):b.reject({message:this.nls.warningsAndErrors.cannotLocate})):this._getNextLocator()?this._addressToLocation(a).then(function(a){b.resolve(a)}):b.reject({message:this.nls.warningsAndErrors.cannotLocate})}),function(a){b.reject(a)});return b},_getNextLocator:function(){var a=!1,b=this._locatorIndex+1;b<this.csvStore._geocodeSources.length&&(this.locator=this._getLocator(b),a=
"undefined"!==typeof this.locator);return a},_flashFeatures:function(a){var b;l.forEach(a,d.hitch(this,function(a){if(a.geometry){var c=E.fromHex(this.styleColor),g=d.clone(c);g.a=.4;c=new t(t.STYLE_CIRCLE,15,new u(u.STYLE_SOLID,c,1),g);a=new F(a.geometry,c);this.map.graphics.add(a);b=a.getLayer?a.getLayer():b;(a=a.getDojoShape())&&A.animateStroke({shape:a,duration:900,color:{start:a.strokeStyle.color,end:a.strokeStyle.color},width:{start:25,end:0}}).play()}}));setTimeout(d.hitch(this,function(b){b&&
b.clear&&(b.clear(),a&&(a[0]._layer&&a[0]._layer.infoTemplate||a[0].infoTemplate)&&(this.map.infoWindow.setFeatures(a),this.map.infoWindow.select(0)))}),1200,b)},_panToAndSelectFeature:function(a){if(a&&a.geometry){var b=this.map.getMaxZoom(),c=Math.round(.25*b);this.map.centerAndZoom(a.geometry,0<b-c?b-c:b).then(d.hitch(this,function(){this._flashFeatures([a])}))}},setStyleColor:function(a){this.styleColor=a},_updateEdit:function(a){this._editDisabled=a;this._updateImageNode("bg-edit","bg-edit-white",
"bg-edit-disabled",this._editDisabled,this.domNode)},_updateCancel:function(a){this._cancelDisabled=a;this._updateImageNode("bg-cancel","bg-cancel-white","bg-cancel-disabled",this._cancelDisabled,this.domNode)},_updateSaveAndCancel:function(a){this._updateSave(a);this._updateCancel(a)},_updateSave:function(a){this._saveDisabled=a;this._updateImageNode("bg-save","bg-save-white","bg-save-disabled",this._saveDisabled,this.domNode)},_updateLocate:function(a){this._locateDisabled=a;this._updateImageNode("bg-locate",
"bg-locate-white","bg-locate-disabled",this._locateDisabled,this.featureView.domNode)},_updateSync:function(a){this._syncDisabled=a;this.featureView.syncFields&&this._updateImageNode("bg-sync","bg-sync-white","bg-sync-disabled",this._syncDisabled,this.featureView.domNode)},updateImageNodes:function(){this._updateImageNode("bg-edit","bg-edit-white","bg-edit-disabled",this._editDisabled,this.domNode);this._updateImageNode("bg-cancel","bg-cancel-white","bg-cancel-disabled",this._cancelDisabled,this.domNode);
this._updateImageNode("bg-save","bg-save-white","bg-save-disabled",this._saveDisabled,this.domNode);this._updateImageNode("bg-locate","bg-locate-white","bg-locate-disabled",this._locateDisabled,this.domNode);this._updateImageNode("bg-sync","bg-sync-white","bg-sync-disabled",this._syncDisabled,this.featureView.domNode)},_updateImageNode:function(a,b,c,d,g){var e=-1<this._darkThemes.indexOf(this.theme),f=d?c:e?b:a,h=e?b:a;d=!1;e=n("."+a,g);e.hasOwnProperty("length")&&0===e.length?e=n("."+c,g):(d=!0,
h=a);!d&&e.hasOwnProperty("length")&&0===e.length?e=n("."+b,g):d||(d=!0,h=c);l.forEach(e,function(a){q.remove(a,h);q.add(a,f)})},updateTheme:function(a){this.theme=a}})});