// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/array dojo/_base/lang dojo/Deferred dojo/promise/all dojo/string esri/arcade/arcade esri/arcade/Feature esri/graphic esri/tasks/RelationshipQuery jimu/utils jimu/LayerStructure".split(" "),function(g,l,m,r,n,p,k,t,u,v,w){var b={readExprInfo:{}};b.readExprInfo.getArcadeProfilesByType=function(a,d,c){a={map:a,layer:d};return"render"===c?b.readExprInfo._getArcadeRender(a):"label"===c?b.readExprInfo._getArcadeLabel(a):"infoTemplate"===c?b.readExprInfo._getArcadeInfoTemplate(a):b.readExprInfo._getAllArcade(a)};
b.readExprInfo._getArcadeRender=function(a){return b.readExprInfo._lookupArcadeRender({layers:b.readExprInfo._checkPassInLayer(a)})};b.readExprInfo._getArcadeInfoTemplate=function(a){return b.readExprInfo._lookupArcadeInfoTemplate({layers:b.readExprInfo._checkPassInLayer(a)})};b.readExprInfo._getArcadeLabel=function(a){return b.readExprInfo._lookupArcadeLabel({layers:b.readExprInfo._checkPassInLayer(a)})};b.readExprInfo._getAllArcade=function(a){var d=b.readExprInfo._getArcadeRender(a),c=b.readExprInfo._getArcadeInfoTemplate(a);
a=b.readExprInfo._getArcadeLabel(a);return{render:d,infoTemplate:c,label:a}};b.readExprInfo._checkPassInLayer=function(a){var d=[];return d="undefined"!==typeof a?"undefined"!==typeof a.layer?null!==a.layer&&""!==a.layer?b.readExprInfo._getAllMapLayers(a):b.readExprInfo._getAllMapLayers():b.readExprInfo._getAllMapLayers():b.readExprInfo._getAllMapLayers()};b.readExprInfo._getAllMapLayers=function(a){var d="",c=[],b=w.getInstance();a&&a.layer&&(d=a.layer.id);""!==d?(a=b.getNodeById(d))&&c.push(a._layerInfo.layerObject):
b.traversal(function(a){"undefined"!==typeof a._layerInfo.layerObject.type?-1===a._layerInfo.layerObject.type.indexOf("tile")&&c.push(a._layerInfo.layerObject):c.push(a._layerInfo.layerObject)});return c};b.readExprInfo._lookupArcadeRender=function(a){var d=[];0<a.layers.length&&g.forEach(a.layers,l.hitch(this,function(a){var b={};if("undefined"!==typeof a.renderer){var c=a.renderer;"undefined"!==typeof c.valueExpression&&(b.layer=a.id,b.valueExpression=c.valueExpression,b.valueExpressionTitle=c.valueExpressionTitle,
"undefined"!==typeof c.values&&(b.values=c.values),"undefined"!==typeof c.visualVariables&&(b.visualVariables=c.visualVariables));1<Object.keys(b).length&&b.constructor===Object?d.push(b):d.push({layer:a.id,valueExpression:null,valueExpressionTitle:null,values:null,visualVariables:null})}}));return d};b.readExprInfo._lookupArcadeInfoTemplate=function(a){var b=[];0<a.layers.length&&g.forEach(a.layers,l.hitch(this,function(a){var d={};if("undefined"!==typeof a.infoTemplate)"undefined"!==typeof a.infoTemplate.info.expressionInfos&&
0<a.infoTemplate.info.expressionInfos.length&&(d.layer=a.id,d.expressionInfos=a.infoTemplate.info.expressionInfos);else if("undefined"!==typeof a.infoTemplates)for(var c in a.infoTemplates)if(a.infoTemplates.hasOwnProperty(c)&&"undefined"!==typeof a.infoTemplates[c].infoTemplate.info.expressionInfos){var h=a.infoTemplates[c].infoTemplate;0<h.info.expressionInfos.length&&(d.layer=a.id,d.expressionInfos=h.info.expressionInfos)}1<Object.keys(d).length&&d.constructor===Object?b.push(d):b.push({layer:a.id,
expressionInfos:null})}));return b};b.readExprInfo._lookupArcadeLabel=function(a){var b=[];0<a.layers.length&&g.forEach(a.layers,l.hitch(this,function(a){var d={};"undefined"!==typeof a.labelingInfo&&g.forEach(a.labelingInfo,l.hitch(this,function(b){"undefined"!==typeof b.name&&(d.layer=a.id,d.name=b.name,d.labelingInfo=b,d.expression=b.labelExpressionInfo.expression)}));1<Object.keys(d).length&&d.constructor===Object?b.push(d):b.push({layer:a.id,name:null,labelingInfo:null,expression:null})}));return b};
b.customExpr={};b.customExpr.getAttributesFromCustomArcadeExpr=function(a,d){d=new k(d,d.geometry);a=b.InfoTemplate._parseArcadeExpressions(a);return b.InfoTemplate._combineFeatureAttributesAndExpressionResolutions(d,a)};b.customExpr.getAttributesValueFromCustomArcadeExprBatch=function(a,d){var c=[],f;for(f in d)c.push(new k(d[f],d[f].geometry));d=b.InfoTemplate._parseArcadeExpressions(a);a=b.InfoTemplate._getExprNamesArrayFromPopupExprInfos(a);a.relationships=null;a.parsedExpressions=d;var e=new m;
b.InfoTemplate._getPopupFieldsValueFromArcadeFeatures(c,a).then(function(a){e.resolve(a)});return e};b.InfoTemplate={};b.InfoTemplate.getAttributesFromInfoTemplate=function(a,d,c){var f=new k(c,c.geometry);a=b.readExprInfo.getArcadeProfilesByType(a,d,"infoTemplate")[0].expressionInfos;if(!a)return c.attributes;c=b.InfoTemplate._parseArcadeExpressions(a);return b.InfoTemplate._combineFeatureAttributesAndExpressionResolutions(f,c)};b.InfoTemplate.getAttributesValueFromInfoTemplateBatch=function(a,d,
c){var f=[],e;for(e in c)f.push(new k(c[e],c[e].geometry));a=b.readExprInfo.getArcadeProfilesByType(a,d,"infoTemplate")[0].expressionInfos;var h=new m;if(!a)return h.resolve([]),h;c=b.InfoTemplate._parseArcadeExpressions(a);e=null;e=d.popupInfo.description;null!==e?(e=b.InfoTemplate._convertPopupDescToFieldNamesArray(e),e.relationships=b.InfoTemplate._getRelationshipQueries(d)):(e=b.InfoTemplate._getExprNamesArrayFromPopupExprInfos(a),e.relationships=null);e.parsedExpressions=c;b.InfoTemplate._getPopupFieldsValueFromArcadeFeatures(f,
e).then(function(a){h.resolve(a)});return h};b.InfoTemplate._getRelationshipQueries=function(a){var b=!1,c={},f=/\d+/,e;if(e=a.popupInfo.description.match(/\{relationships\/\d+\//gm))b=!0,g.forEach(e,function(b){var d=b.match(f)[0];c.hasOwnProperty(d)||(b=new u,b.outFields=["*"],b.relationshipId=d,b.returnGeometry=!1,c[d]={operLayer:a,relatedQuery:b})});return b?c:null};b.InfoTemplate._getExprNamesArrayFromPopupExprInfos=function(a){var b=[],c;for(c in a)b.push("${expression/"+a[c].name+"}");return b};
b.InfoTemplate._convertPopupDescToFieldNamesArray=function(a){a=b.InfoTemplate._convertEndParasToEOLs(a);a=b.InfoTemplate._convertBreaksToEOLs(a);a=b.InfoTemplate._sanitizeNoTags(a).trim();a=a.replace(/\{/gi,"${");a=a.replace(/\u00a0/gi," ");a=a.split("\n");return a=g.map(a,function(a){return a.trim()})};b.InfoTemplate._sanitizeNoTags=function(a){var b;b=v.sanitizeHTML(a);a=/<(?:!--(?:(?:-*[^->])*--+|-?)|script\b(?:[^"'>]|"[^"]*"|'[^']*')*>[\s\S]*?<\/script\s*|style\b(?:[^"'>]|"[^"]*"|'[^']*')*>[\s\S]*?<\/style\s*|\/?[a-z](?:[^"'>]|"[^"]*"|'[^']*')*)>/gi;
var c;do c=b,b=b.replace(a,"");while(b!==c);return b=b.replace(/</g,"\x26lt;")};b.InfoTemplate._getPopupFieldsValueFromArcadeFeatures=function(a,d){var c=new m,f=[],e=[],h=0;d.relationships?(g.forEach(a,function(a){b.InfoTemplate._objEach(d.relationships,function(c,f){var h=new m,l=c.relatedQuery,k;e.push(h);k=a.attributes[c.operLayer.layerObject.objectIdField];l.objectIds=[k];c.operLayer.layerObject.queryRelatedFeatures(l,function(c){var e=[];c[k]&&c[k].features&&(c=c[k].features,g.forEach(c,function(c){var h=
[],k,l,m,q;k=a.attributes;l="relationships/"+f+"/";b.InfoTemplate._objEach(c.attributes,function(a,b){m=l+b;k[m]=a});q=new t(a.geometry,null,k);g.forEach(d,function(a){h.push(n.substitute(a,b.InfoTemplate._combineFeatureAttributesAndExpressionResolutions(q,d.parsedExpressions),b.InfoTemplate._useEmptyStringForNull))});e.push(h)}));h.resolve(e)})})}),r(e).then(function(a){g.forEach(a,function(a){g.forEach(a,function(a){++h;f.push(a)})});console.log(h+" related address features found");c.resolve(f)})):
(g.forEach(a,function(a){var c=[];g.forEach(d,function(e){c.push(n.substitute(e,b.InfoTemplate._combineFeatureAttributesAndExpressionResolutions(a,d.parsedExpressions),b.InfoTemplate._useEmptyStringForNull))});f.push(c)}),c.resolve(f));return c};b.InfoTemplate._parseArcadeExpressions=function(a){var b;Array.isArray(a)&&0<a.length&&(b={},g.forEach(a,function(a){b[a.name]=p.parseScript(a.expression)}));return b};b.InfoTemplate._initArcadeContext=function(a){var b={vars:{}};b.vars.$feature=new k(a);
return b};b.InfoTemplate._combineFeatureAttributesAndExpressionResolutions=function(a,d){var c,f,e;c=l.mixin({},a.attributes);if(d)for(f in a=b.InfoTemplate._initArcadeContext(a),d)e=p.executeScript(d[f],a),c["expression/"+f]=e?e.toString():"";return c};b.InfoTemplate._convertEndParasToEOLs=function(a){var b=a;a=a.match(/<\/p>/gi);g.forEach(a,function(a){b=b.replace(a,"\n")});return b};b.InfoTemplate._convertBreaksToEOLs=function(a){var b=a;a=a.match(/<br\s*\/?>/gi);g.forEach(a,function(a){b=b.replace(a,
"\n")});return b};b.InfoTemplate._useEmptyStringForNull=function(a){return a?a:""};b.InfoTemplate._objEach=function(a,b,c){for(var d in a)a.hasOwnProperty(d)&&b.call(c,a[d],d)};return b});