// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("exports dojo/_base/lang dojo/_base/array dojo/_base/html dojo/has dojo/Deferred jimu/utils esri/lang esri/tasks/QueryTask esri/tasks/query".split(" "),function(e,n,p,v,u,r,t,x,y,z){function w(b){var a=n.clone(b.attributes);(b=b.geometry)&&"point"===b.type&&("x"in a?a._x=b.x:a.x=b.x,"y"in a?a._y=b.y:a.y=b.y);return a}e.exportCSV=function(b,a,c){return e._createCSVStr(a,c).then(function(a){return e._download(b+".csv",a)})};e.exportCSVFromFeatureLayer=function(b,a,c){c=c||{};return e._getExportData(a,
{datas:c.datas,objectIds:c.objectIds,fromClient:c.fromClient,withGeometry:c.withGeometry,outFields:c.outFields,filterExpression:c.filterExpression,outSpatialReference:c.outSpatialReference}).then(function(d){return e._formattedData(a,d,{formatNumber:c.formatNumber,formatDate:c.formatDate,formatCodedValue:c.formatCodedValue,richText:{clearFormat:c.richTextFieldsToClear&&!!c.richTextFieldsToClear.length,fieldsToClear:c.richTextFieldsToClear||[]},popupInfo:c.popupInfo}).then(function(a){return e.exportCSV(b,
a.datas,a.columns)})})};e.exportCSVByAttributes=function(b,a,c,d){d=n.mixin({},d);d.datas=c;return e.exportCSVFromFeatureLayer(b,a,d)};e.exportCSVByGraphics=function(b,a,c,d){c=p.map(c,function(a){return a.attributes});return e.exportCSVByAttributes(b,a,c,d)};e._createCSVStr=function(b,a){var c=new r,d="",e=0,f=0,g="",h="";try{a=p.map(a,function(a){return"string"===typeof a?{name:a}:a});p.forEach(a,function(a){a=a.alias||a.name;-1<a.toString().indexOf(",")&&(a='"'+a+'"');d=d+g+a;g=","});for(var d=
d+"\r\n",e=b.length,f=a.length,l=0;l<e;l++){for(var g="",k=0;k<f;k++)(h=b[l][a[k].name])||"number"===typeof h||(h=""),h&&/[",\r\n]/g.test(h)&&(h='"'+h.replace(/(")/g,'""')+'"'),d=d+g+h,g=",";d+="\r\n"}c.resolve(d)}catch(q){console.error(q),c.resolve("")}return c};e._isIE11=function(){return 11===t.has("ie")};e._isEdge=function(){return t.has("edge")};e._getDownloadUrl=function(b){return window.Blob&&window.URL&&window.URL.createObjectURL?(b=new Blob(["\ufeff"+b],{type:"text/csv"}),URL.createObjectURL(b)):
"data:attachment/csv;charset\x3dutf-8,\ufeff"+encodeURIComponent(b)};e._download=function(b,a){var c=new r;try{if(u("ie")&&10>u("ie")){var d=window.top.open("about:blank","_blank");d.document.write("sep\x3d,\r\n"+a);d.document.close();d.document.execCommand("SaveAs",!0,b);d.close()}else if(10===u("ie")||e._isIE11()||e._isEdge()){var m=new Blob(["\ufeff"+a],{type:"text/csv"});navigator.msSaveBlob(m,b)}else{var f=v.create("a",{href:e._getDownloadUrl(a),target:"_blank",download:b},document.body);if(u("safari")){var g=
document.createEvent("MouseEvents");g.initEvent("click",!0,!0);f.dispatchEvent(g)}else f.click();v.destroy(f)}c.resolve()}catch(h){c.reject(h)}return c};e._getExportData=function(b,a){var c=new r,d=null,m=[],f=a.datas,g=a.withGeometry,d=a.outFields;d&&d.length||(d=b.fields);d=n.clone(d);if(g&&!(f&&0<f.length)){var m=n.clone(d),h="",h=-1!==d.indexOf("x")?"_x":"x";d.push({name:h,alias:h,format:{digitSeparator:!1,places:6},show:!0,type:"esriFieldTypeDouble"});h=-1!==d.indexOf("y")?"_y":"y";d.push({name:h,
alias:h,format:{digitSeparator:!1,places:6},show:!0,type:"esriFieldTypeDouble"})}f&&0<f.length?c.resolve({data:f||[],outFields:d}):a.fromClient?(f=p.map(b.graphics,function(a){return g?w(a):n.clone(a)}),c.resolve({data:f||[],outFields:d})):e._getExportDataFromServer(b,m,a).then(function(a){c.resolve({data:a||[],outFields:d})});return c};e._getExportDataFromServer=function(b,a,c){var d=new r;if("esri.layers.FeatureLayer"!==b.declaredClass)return d.resolve([]),d;var e=new y(b.url),f=new z;f.where=c.filterExpression||
b.getDefinitionExpression&&b.getDefinitionExpression()||"1\x3d1";0<a.length?(b=p.map(a,function(a){return a.name}),f.outFields=b):f.outFields=["*"];f.objectIds=c.objectIds;f.returnGeometry=c.withGeometry;f.outSR=c.spatialReference;e.execute(f,function(a){a=p.map(a.features,function(a){return w(a)});d.resolve(a)},function(a){console.error(a);d.resolve([])});return d};e._formattedData=function(b,a,c){var d=new r,m=[],f=a.data;a=a.outFields;for(var g=0,h=f.length;g<h;g++){for(var l={},k=0;k<a.length;k++){var q=
a[k];l[q.name]=e._getExportValue(f[g][q.name],q,b.objectIdField,b.typeIdField,f[g][b.typeIdField],b.types,c)}m.push(l)}b=p.map(a,function(a){return{alias:a.alias,name:a.name}});d.resolve({datas:m,columns:b});return d};e._getExportValue=function(b,a,c,d,e,f,g){function h(a){if(k&&x.isDefined(k.fieldInfos))for(var b=0,c=k.fieldInfos.length;b<c;b++){var d=k.fieldInfos[b];if(d.fieldName===a)return d.format}return null}function l(a){for(var b=0,c=q.length;b<c;b++)if(q[b].fieldName===a)return!0;return!1}
var k=g.popupInfo,q=g.richText.fieldsToClear,m=!!a.domain&&g.formatCodedValue,n="esriFieldTypeDate"===a.type&&g.formatDate,r=c&&a.name===c;d=d&&a.name===d;l="esriFieldTypeString"===a.type&&g.richText.clearFormat&&l(a.name);return n?t.fieldFormatter.getFormattedDate(b,h(a.name)):d?t.fieldFormatter.getTypeName(b,f):m?t.fieldFormatter.getCodedValue(a.domain,b):l?b?(a=document.createElement("span"),a.innerHTML=b,a.textContent||a.innerText||""):b:m||n||r||d||l?b:(g=null,c&&f&&0<f.length&&(c=(c=p.filter(f,
function(a){return a.id===e}))&&c[0])&&c.domains&&c.domains[a.name]&&c.domains[a.name].codedValues&&(g=t.fieldFormatter.getCodedValue(c.domains[a.name],b)),null!==g?g:b)}});